/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
	Ok you can modify it manually, but be smart about it. Backups.
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,4)
#endif


#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class AUSQLDB : public AInfo
{
private:
	AUSQLDB();
	//~AUSQLDB();
public:
	FPointer ServerPointer;
	FPointer ResultPointer;
	DECLARE_FUNCTION(execSQLServerConnect);
	DECLARE_FUNCTION(execGetQueries);
	DECLARE_FUNCTION(execSQLExecute);
	DECLARE_FUNCTION(execSQLExecuteQuery);
    DECLARE_CLASS(AUSQLDB,AInfo,0,USQL);
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ABlankActor)
#endif // VERIFY_CLASS_SIZES